# Generated by Django 4.2.28 on 2026-03-03 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('ACCOUNTS', 'Accounts'), ('PRODUCTS', 'Products'), ('RFQ', 'RFQ'), ('COSTING', 'Costing'), ('SALES', 'Sales'), ('BUDGET', 'Budget'), ('PROCUREMENT', 'Procurement'), ('SETTINGS', 'Settings')], max_length=20)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('STATUS_CHANGE', 'Status Changed'), ('SUBMIT', 'Submitted'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('ACCEPT', 'Accepted'), ('SEND', 'Sent'), ('ISSUE', 'Issued'), ('COMPLETE', 'Completed'), ('CLOSE', 'Closed'), ('RECALCULATE', 'Recalculated'), ('SAVE_VERSION', 'Version Saved'), ('EXPORT', 'Exported'), ('LOGIN', 'Logged In'), ('LOGOUT', 'Logged Out')], max_length=20)),
                ('object_type', models.CharField(help_text='e.g. RFQ, PurchaseOrder', max_length=80)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, default='', help_text='Human-readable representation, e.g. PO-202603-0001', max_length=300)),
                ('old_status', models.CharField(blank=True, default='', max_length=30)),
                ('new_status', models.CharField(blank=True, default='', max_length=30)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Extra context')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['module', 'action'], name='accounts_au_module_394f59_idx'), models.Index(fields=['object_type', 'object_id'], name='accounts_au_object__353b30_idx')],
            },
        ),
    ]
