# Generated by Django 4.2.28 on 2026-03-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='reference',
            field=models.CharField(blank=True, default='', help_text='Related document/invoice reference, e.g. INV-EF-202603-004', max_length=300),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='remarks',
            field=models.TextField(blank=True, default='', help_text='Free-text notes for additional context'),
        ),
    ]
