# Generated by Django 4.2.28 on 2026-03-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_reference_remarks_to_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGEMENT', 'Management'), ('SALES', 'Sales'), ('PURCHASING', 'Purchasing')], default='SALES', help_text='Determines permissions across all modules.', max_length=20),
        ),
    ]
