# Generated by Django 4.2.28 on 2026-03-11 00:35

from django.db import migrations


def migrate_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    # Map old roles to new roles
    mapping = {
        'ADMIN': 'MANAGEMENT',
        'MANAGER': 'MANAGEMENT',
        'FINANCE': 'MANAGEMENT',
        'PROCUREMENT': 'PURCHASING',
        'VIEWER': 'SALES',
    }
    for old_role, new_role in mapping.items():
        User.objects.filter(role=old_role).update(role=new_role)


def migrate_roles_reverse(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='MANAGEMENT').update(role='ADMIN')
    User.objects.filter(role='PURCHASING').update(role='PROCUREMENT')
    User.objects.filter(role='SALES').update(role='VIEWER')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role_and_status_changes'),
    ]

    operations = [
        migrations.RunPython(migrate_roles, migrate_roles_reverse),
    ]
