# Generated by Django 6.0.2 on 2026-03-12 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('rfq_created', 'New RFQ'), ('rfq_updated', 'RFQ Updated'), ('costing_created', 'Costing Created'), ('costing_updated', 'Costing Updated'), ('quotation_sent', 'Quotation Sent'), ('quotation_won', 'Quotation Won'), ('quotation_rejected', 'Quotation Rejected'), ('sales_order', 'Sales Order'), ('budget_created', 'Budget Created'), ('budget_approved', 'Budget Approved'), ('budget_rejected', 'Budget Rejected'), ('procurement', 'Procurement'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('reference_id', models.CharField(blank=True, default='', help_text='E.g. RFQ number, SO number, etc.', max_length=50)),
                ('reference_url', models.CharField(blank=True, default='', help_text='Frontend path to navigate to when clicked.', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
