# Generated by Django 6.0.2 on 2026-03-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit / internal code — auto-generated if left empty', max_length=50, unique=True),
        ),
    ]
