# Generated by Django 4.2.28 on 2026-03-03 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0001_initial'),
        ('products', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rfq',
            field=models.ForeignKey(blank=True, help_text='The RFQ this product is planned for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='rfq.rfq'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='The supplier this product will be sourced from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='rfq.supplier'),
        ),
    ]
