# Generated by Django 4.2.28 on 2026-03-03 01:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('delivery_days', models.PositiveIntegerField(default=0)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=255)),
                ('validity_days', models.PositiveIntegerField(default=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['total_amount'],
            },
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('project_title', models.CharField(blank=True, default='', max_length=255)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('SENT', 'Sent to Suppliers'), ('RECEIVED', 'Quotations Received'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RFQ',
                'verbose_name_plural': 'RFQs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveIntegerField(default=1)),
                ('item_name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('model_number', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('specifications', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_items', to='products.product')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rfq.rfq')),
            ],
            options={
                'ordering': ['item_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='rfq',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='rfqs', to='rfq.supplier'),
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('SAME', 'Same as per requirement'), ('COUNTER', 'Counter-offer')], default='SAME', max_length=20)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('model_number', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_type', models.CharField(choices=[('VAT_INC', 'VAT Inclusive'), ('VAT_EX', 'VAT Exclusive'), ('VAT_EXEMPT', 'VAT Exempt')], default='VAT_INC', max_length=20)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('unit_price_vat_ex', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('availability', models.CharField(blank=True, choices=[('ON_STOCK', 'On-Stock'), ('ORDER_BASIS', 'Order Basis')], default='', max_length=20)),
                ('availability_detail', models.CharField(blank=True, default='', help_text="e.g. '30 to 45 Days'", max_length=255)),
                ('warranty_period', models.CharField(blank=True, choices=[('6MOS', '6 Months'), ('1YR', '1 Year'), ('3YRS', '3 Years'), ('5YRS', '5 Years'), ('OTHER', 'Other')], default='', max_length=10)),
                ('warranty_detail', models.CharField(blank=True, default='', max_length=255)),
                ('price_validity', models.CharField(blank=True, default='', help_text="e.g. '15 days'", max_length=100)),
                ('tax_type', models.CharField(blank=True, default='', help_text='Tax type/computation from supplier proposal', max_length=255)),
                ('remarks', models.TextField(blank=True, default='', help_text='e.g. VAT Inclusive / VAT Exclusive')),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('price_proposal', models.FileField(blank=True, null=True, upload_to='quotations/price_proposals/%Y/%m/')),
                ('delivery_days', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rfq.quotation')),
                ('rfq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoted_items', to='rfq.rfqitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='rfq.rfq'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='rfq.supplier'),
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for Revision')], max_length=20)),
                ('level', models.PositiveIntegerField(default=1)),
                ('comments', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='rfq.rfq')),
            ],
            options={
                'ordering': ['rfq', 'level', '-created_at'],
            },
        ),
    ]
