# Generated by Django 4.2.28 on 2026-03-01 05:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Select from product catalog (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
