# Generated by Django 4.2.28 on 2026-03-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_FOR_CANVASS', 'Pending for Canvass'), ('SENT', 'Sent to Suppliers'), ('RECEIVED', 'Quotations Received'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='DRAFT', max_length=30),
        ),
    ]
