# Generated by Django 4.2.28 on 2026-03-11 00:35

from django.db import migrations


def migrate_rfq_status(apps, schema_editor):
    RFQ = apps.get_model('rfq', 'RFQ')
    RFQ.objects.filter(status='PENDING').update(status='PENDING_FOR_CANVASS')


def migrate_rfq_status_reverse(apps, schema_editor):
    RFQ = apps.get_model('rfq', 'RFQ')
    RFQ.objects.filter(status='PENDING_FOR_CANVASS').update(status='PENDING')


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0002_role_and_status_changes'),
    ]

    operations = [
        migrations.RunPython(migrate_rfq_status, migrate_rfq_status_reverse),
    ]
