# Generated by Django 6.0.2 on 2026-03-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0003_migrate_rfq_status_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='viber',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='supplier',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
