# Generated by Django 6.0.2 on 2026-03-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0004_supplier_facebook_supplier_viber_supplier_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_FOR_CANVASS', 'Pending for Canvass'), ('CANVASS_DONE', 'Canvass Complete'), ('SENT', 'Sent to Suppliers'), ('RECEIVED', 'Quotations Received'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='DRAFT', max_length=30),
        ),
    ]
