# Generated by Django 4.2.28 on 2026-03-03 01:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('default_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('has_input_vat', models.BooleanField(default=False, help_text='If checked, this category contributes to Input VAT computation')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'cost categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CostingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('project_title', models.CharField(blank=True, default='', max_length=255)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('warranty', models.CharField(blank=True, default='', max_length=255)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contingency_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('contingency_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_project_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costing_sheets_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costing_sheets_created', to=settings.AUTH_USER_MODEL)),
                ('rfq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costing_sheets', to='rfq.rfq')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('overrides', models.JSONField(default=dict)),
                ('projected_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('projected_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('projected_margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('costing_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='costing.costingsheet')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostingMarginLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('facilitation_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('desired_margin_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('jv_cost_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cost_of_money_percent', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('municipal_tax_percent', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('others_1_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('others_1_label', models.CharField(default='Others 1', max_length=100)),
                ('others_2_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('others_2_label', models.CharField(default='Others 2', max_length=100)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('withholding_tax_percent', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('creditable_tax_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('warranty_security_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('facilitation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('desired_margin_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('jv_cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost_of_money_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('municipal_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('others_1_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('others_2_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_selling_vat_ex', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_selling_vat_inc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('withholding_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creditable_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('warranty_security_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_govt_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('municipal_tax_revenue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_take_home', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('earning_before_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('output_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('input_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_payable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('earning_after_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('costing_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margin_levels', to='costing.costingsheet')),
            ],
            options={
                'ordering': ['costing_sheet', 'label'],
                'unique_together': {('costing_sheet', 'label')},
            },
        ),
        migrations.CreateModel(
            name='CostingLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='costing.costcategory')),
                ('costing_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='costing.costingsheet')),
                ('quotation_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rfq.quotationitem')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rfq.supplier')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CostingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot_data', models.JSONField()),
                ('change_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('costing_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='costing.costingsheet')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['costing_sheet', '-version_number'],
                'unique_together': {('costing_sheet', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='CostingCommissionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('margin_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_splits', to='costing.costingmarginlevel')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costing.commissionrole')),
            ],
            options={
                'ordering': ['role__sort_order'],
                'unique_together': {('margin_level', 'role')},
            },
        ),
    ]
