# Generated by Django 4.2.28 on 2026-02-28 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rfq', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_number', models.CharField(help_text='Auto-generated or user-defined costing sheet reference', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, help_text='Current version number (auto-incremented on save)')),
                ('total_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_logistics_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_margin_percent', models.DecimalField(decimal_places=2, default=20.0, help_text='Desired profit margin percentage', max_digits=5)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, help_text='Calculated: total_cost / (1 - margin%)', max_digits=14)),
                ('actual_margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costing_sheets_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costing_sheets_created', to=settings.AUTH_USER_MODEL)),
                ('rfq', models.ForeignKey(blank=True, help_text='Source RFQ for supplier pricing data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costing_sheets', to='rfq.rfq')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Supplier B + Air Freight'", max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('overrides', models.JSONField(default=dict, help_text='JSON dict mapping line_item_id -> {field: new_value}')),
                ('projected_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('projected_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('projected_margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('costing_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='costing.costingsheet')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostingLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('MATERIAL', 'Material'), ('LABOR', 'Labor'), ('OVERHEAD', 'Overhead'), ('LOGISTICS', 'Logistics'), ('OTHER', 'Other')], default='MATERIAL', max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('logistics_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('costing_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='costing.costingsheet')),
                ('quotation_item', models.ForeignKey(blank=True, help_text='Linked quotation item for auto-pricing', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rfq.quotationitem')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rfq.supplier')),
            ],
            options={
                'ordering': ['cost_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CostingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot_data', models.JSONField(help_text='JSON snapshot of the costing sheet and all line items at this version')),
                ('change_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('costing_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='costing.costingsheet')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['costing_sheet', '-version_number'],
                'unique_together': {('costing_sheet', 'version_number')},
            },
        ),
    ]
