# Generated by Django 6.0.2 on 2026-03-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costingsheet',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Default commission rate (%) applied to margin levels', max_digits=5),
        ),
        migrations.AlterField(
            model_name='costingmarginlevel',
            name='label',
            field=models.CharField(choices=[('VERY_LOW', 'Very Low'), ('LOW', 'Low'), ('MEDIUM_LOW', 'Medium-Low'), ('MEDIUM_HIGH', 'Medium-High'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], max_length=15),
        ),
    ]
