# Generated by Django 6.0.2 on 2026-03-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0002_costingsheet_commission_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costingmarginlevel',
            name='label',
            field=models.CharField(choices=[('VERY_LOW', 'Very Low'), ('LOW', 'Low'), ('MEDIUM_LOW', 'Medium-Low'), ('MEDIUM_HIGH', 'Medium-High'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High'), ('CUSTOM', 'Custom')], max_length=15),
        ),
    ]
