# Generated by Django 4.2.28 on 2026-03-03 01:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormalQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('client_name', models.CharField(max_length=255)),
                ('client_address', models.TextField(blank=True, default='')),
                ('client_contact', models.CharField(blank=True, default='', max_length=255)),
                ('client_email', models.EmailField(blank=True, default='', max_length=254)),
                ('project_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('warranty', models.CharField(blank=True, default='', max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('payment_terms', models.TextField(blank=True, default='')),
                ('delivery_terms', models.TextField(blank=True, default='')),
                ('validity_days', models.PositiveIntegerField(default=30)),
                ('terms_and_conditions', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Client'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REVISED', 'Revised')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('costing_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formal_quotations', to='costing.costingsheet')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formal_quotations_created', to=settings.AUTH_USER_MODEL)),
                ('margin_level', models.ForeignKey(blank=True, help_text='Which margin scenario was selected for pricing', null=True, on_delete=django.db.models.deletion.SET_NULL, to='costing.costingmarginlevel')),
                ('rfq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formal_quotations', to='rfq.rfq')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('client_name', models.CharField(max_length=255)),
                ('project_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('contract_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('awarded_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('costing_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costing.costingsheet')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_created', to=settings.AUTH_USER_MODEL)),
                ('formal_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='sales.formalquotation')),
                ('rfq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rfq.rfq')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormalQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('model_number', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.formalquotation')),
            ],
            options={
                'ordering': ['item_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Direct to End-User', 'JVA Partner View'", max_length=255)),
                ('contract_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_ex_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('warranty_security', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ewt_amount', models.DecimalField(decimal_places=2, default=0, help_text='5% EWT', max_digits=14)),
                ('lgu_amount', models.DecimalField(decimal_places=2, default=0, help_text='2% LGU', max_digits=14)),
                ('facilitation', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('implementation', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_cash_flow_percent', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('net_benefit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('output_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('input_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_payable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_analyses', to='sales.salesorder')),
            ],
            options={
                'verbose_name_plural': 'contract analyses',
                'ordering': ['sales_order', 'id'],
            },
        ),
    ]
