# Generated by Django 6.0.2 on 2026-03-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_quotationrevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalquotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Client'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REVISED', 'Revised'), ('WON', 'Won')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationrevision',
            name='margin_level_label',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
