# Generated by Django 4.2.28 on 2026-03-03 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total approved budget amount', max_digits=14)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total actually spent (from PO actuals)', max_digits=14)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, help_text='Allocated - Spent', max_digits=14)),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_approved', to=settings.AUTH_USER_MODEL)),
                ('costing_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='costing.costingsheet')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_created', to=settings.AUTH_USER_MODEL)),
                ('rfq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='rfq.rfq')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
