# Generated by Django 4.2.28 on 2026-03-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualcost',
            name='cost_type',
            field=models.CharField(choices=[('MATERIAL', 'Material'), ('LABOR', 'Labor'), ('OVERHEAD', 'Overhead'), ('LOGISTICS', 'Logistics'), ('SHIPPING', 'Shipping'), ('TAX', 'Tax'), ('OTHER', 'Other')], default='MATERIAL', max_length=20),
        ),
    ]
